// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9c9ncz3qQ2yr9u0T952mRZWP4oowhpH4',
    appId: '1:24536221096:web:36503bc51a1106b077899d',
    messagingSenderId: '24536221096',
    projectId: 'movie-app-p',
    authDomain: 'movie-app-p.firebaseapp.com',
    storageBucket: 'movie-app-p.firebasestorage.app',
    measurementId: 'G-WHYWQYRMKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1OAGEOAaEXuHnZaajgXX0PAYFzprGObg',
    appId: '1:24536221096:android:44394844f97204a177899d',
    messagingSenderId: '24536221096',
    projectId: 'movie-app-p',
    storageBucket: 'movie-app-p.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKacs7KRwJ5fdP4bfpQlOwOKbAwr_C8BU',
    appId: '1:24536221096:ios:143589a911e163d077899d',
    messagingSenderId: '24536221096',
    projectId: 'movie-app-p',
    storageBucket: 'movie-app-p.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKacs7KRwJ5fdP4bfpQlOwOKbAwr_C8BU',
    appId: '1:24536221096:ios:143589a911e163d077899d',
    messagingSenderId: '24536221096',
    projectId: 'movie-app-p',
    storageBucket: 'movie-app-p.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9c9ncz3qQ2yr9u0T952mRZWP4oowhpH4',
    appId: '1:24536221096:web:674f92aec90a194277899d',
    messagingSenderId: '24536221096',
    projectId: 'movie-app-p',
    authDomain: 'movie-app-p.firebaseapp.com',
    storageBucket: 'movie-app-p.firebasestorage.app',
    measurementId: 'G-B0EES6Q9HY',
  );
}
